version: "3.8"
services:
  db:
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE="mysql-docker"
      - MYSQL_USER="root"
      - MYSQL_PASSWORD="root"
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_ROOT_HOST="localhost"
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
# version: "3.8"

# services:
#   db:
#     image: mysql
#     cap_add:
#       - SYS_NICE
#     restart: always
#     environment:
#       MYSQL_DATABASE: "mysql-docker"
#       MYSQL_USER: "root"
#       MYSQL_ROOT_PASSWORD: "root"
#       MYSQL_PASSWORD: "root"
#     ports:
#       - "3306:3306"
#     volumes:
#       - db:/var/lib/mysql
#       - ./db/init.sql:/docker-entrypoint-initdb.sql
# volumes:
#   db:
#     driver: local
# version: "3.1"

# services:
#   db:
#     image: mysql
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root

#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 3306:3306
